name: Bun Update

on:
  schedule:
    # Run before Dependabot (Dependabot is scheduled at 02:00 UTC on Sunday)
    - cron: "30 1 * * 0"
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  update-deps:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Install deps
        run: bun install

      - name: Update deps (bun)
        run: bun update

      - name: Generate lockfile
        run: bun install --frozen-lockfile=false

      - name: Run checks (non-blocking)
        run: |
          set +e
          bun run check || true

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v7
        with:
          branch: chore/bun-update
          title: 'chore(deps): bun update'
          commit-message: 'chore(deps): bun update'
          body: |
            Automated dependency update via `bun update`.

            - Ran `bun install && bun update`
            - Generated fresh `bun.lock` file
            - Executed `bun run check` (non-blocking)
          labels: dependencies
          signoff: true


