# Auto-formatting workflow for ClubOS
# Automatically formats code and creates PR with changes

name: 🎨 Auto Format

on:
  workflow_dispatch: # Allow manual trigger
  schedule:
    - cron: '0 2 * * 1' # Run every Monday at 2 AM UTC

permissions:
  contents: write
  pull-requests: write

jobs:
  format:
    name: 🎨 Format Code
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: 📂 Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: 🏗️ Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: 1.2.20

      - name: 📦 Install dependencies
        run: bun install --frozen-lockfile

      - name: 💅 Run Prettier
        run: bun run format

      - name: 🔧 Run ESLint with auto-fix
        run: bun run lint:fix

      - name: 📝 Check for changes
        id: check-changes
        run: |
          if [ -n "$(git status --porcelain)" ]; then
            echo "changes=true" >> $GITHUB_OUTPUT
            echo "Files that would be formatted:" >> $GITHUB_STEP_SUMMARY
            git status --porcelain >> $GITHUB_STEP_SUMMARY
          else
            echo "changes=false" >> $GITHUB_OUTPUT
            echo "✅ No formatting changes needed!" >> $GITHUB_STEP_SUMMARY
          fi

      - name: 🔄 Create Pull Request
        if: steps.check-changes.outputs.changes == 'true'
        uses: peter-evans/create-pull-request@v7
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: '🎨 chore: auto-format code with prettier and eslint'
          title: '🎨 Auto-format: Code formatting updates'
          body: |
            ## 🎨 Automated Code Formatting

            This PR contains automated formatting changes:

            - ✅ Prettier formatting applied
            - ✅ ESLint auto-fixes applied  
            - ✅ Import statements sorted
            - ✅ Tailwind classes organized

            ### 🤖 Auto-generated
            This PR was automatically created by the formatting workflow.

            **Safe to merge** ✅ - These are only style changes with no functional impact.
          branch: auto-format/prettier-eslint
          delete-branch: true
          labels: |
            🎨 formatting
            🤖 automated
            📦 maintenance
