name: Supabase Keepalive

on:
  schedule:
    # Every 6 days at 03:17 UTC (prevents free-tier project pausing)
    - cron: "17 3 */6 * *"
  workflow_dispatch:

concurrency:
  group: supabase-keepalive-${{ github.ref }}
  cancel-in-progress: true

jobs:
  ping:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
      
      - name: Ping Supabase instance
        env:
          PUBLIC_SUPABASE_URL: ${{ secrets.PUBLIC_SUPABASE_URL }}
          PUBLIC_SUPABASE_ANON_KEY: ${{ secrets.PUBLIC_SUPABASE_ANON_KEY }}
        run: bash scripts/supabase-keepalive.sh


