name: Supabase Keepalive

on:
  schedule:
    # Every 6 days at 03:17 UTC
    - cron: "17 3 */6 * *"
  workflow_dispatch:

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping Supabase REST (health)
        env:
          PUBLIC_SUPABASE_URL: ${{ secrets.PUBLIC_SUPABASE_URL }}
        run: |
          set -euo pipefail
          BASE_URL="${PUBLIC_SUPABASE_URL:-}"
          if [ -z "$BASE_URL" ]; then
            echo "Missing PUBLIC_SUPABASE_URL secret" >&2
            exit 1
          fi
          # Try the platform health endpoint first (does not require auth)
          if curl --retry 3 --retry-connrefused --max-time 20 -fsS "$BASE_URL/health" >/dev/null; then
            echo "Supabase health endpoint responded"
            exit 0
          fi
          # Fallback: ping REST schema endpoint anonymously
          curl --retry 3 --retry-connrefused --max-time 20 -fsS -o /dev/null "$BASE_URL/rest/v1/" || \
          curl --retry 3 --retry-connrefused --max-time 20 -fsS -o /dev/null "$BASE_URL/auth/v1/health"
          echo "Supabase ping sent"


