name: Supabase Keepalive (disabled - replaced by Vercel cron)

# This workflow is intentionally disabled. The project now uses Vercel Cron
# to hit the SvelteKit /api/keep-alive endpoint. You can still run this
# manually if needed via the "Run workflow" button.

on:
  workflow_dispatch:

concurrency:
  group: supabase-keepalive-${{ github.ref }}
  cancel-in-progress: true

jobs:
  ping:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
      
      - name: Skip (workflow disabled)
        run: echo "Supabase keepalive workflow disabled; using Vercel cron instead."


